apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: local
build:
  artifacts:
    - image: sayed/local
      docker:
        dockerfile: Dockerfile
manifests:
  rawYaml:
    - target/classes/META-INF/dekorate/kubernetes.yml
    - k8s/mysql-deployment.yaml
    - k8s/mysql-pv.yaml
    - k8s/redis-config.yaml
    - k8s/redis-pod.yaml
    - k8s/zookeeper.yml
    - k8s/kafka-service.yml
portForward:
  - resourceType: deployment
    resourceName: local
    namespace: default
    port: 8080
    localPort: 9000
  - resourceType: deployment
    resourceName: mysql
    namespace: default
    port: 3306
    localPort: 3306
  - resourceType: pod
    resourceName: redis
    namespace: default
    port: 6379
    localPort: 6380
  - resourceType: deployment
    resourceName: zookeeper
    namespace: default
    port: 2181
    localPort: 2181
  - resourceType: service
    resourceName: kafka-service
    namespace: default
    port: 9092
    localPort: 9092