---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.dekorate.io/vcs-url: <<unknown>>
    app.dekorate.io/commit-id: 5ecda9d27a0dcc07d30705c7c4328cf587299f15
  labels:
    app.kubernetes.io/name: local
    app.kubernetes.io/version: 0.0.1-SNAPSHOT
  name: local
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: local
      app.kubernetes.io/version: 0.0.1-SNAPSHOT
  template:
    metadata:
      annotations:
        app.dekorate.io/vcs-url: <<unknown>>
        app.dekorate.io/commit-id: 5ecda9d27a0dcc07d30705c7c4328cf587299f15
      labels:
        app.kubernetes.io/name: local
        app.kubernetes.io/version: 0.0.1-SNAPSHOT
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: sayed/local:0.0.1-SNAPSHOT
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/health/liveness
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 0
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 10
          name: local
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/health/readiness
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 0
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: local-service
spec:
  selector:
    app.kubernetes.io/name: local
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    app.dekorate.io/vcs-url: <<unknown>>
    app.dekorate.io/commit-id: 5ecda9d27a0dcc07d30705c7c4328cf587299f15
  labels:
    app.kubernetes.io/name: local
    app.kubernetes.io/version: 0.0.1-SNAPSHOT
  name: local
spec:
  rules:
    - host: ""
