---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.dekorate.io/vcs-url: <<unknown>>
    app.dekorate.io/commit-id: 9028e8e2ff5bc0171661cca72ab8acd7fe42ebd6
  labels:
    app.kubernetes.io/name: local
    app.kubernetes.io/version: 0.0.1-SNAPSHOT
  name: local
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: local
      app.kubernetes.io/version: 0.0.1-SNAPSHOT
  template:
    metadata:
      labels:
        app.kubernetes.io/name: local
        app.kubernetes.io/version: 0.0.1-SNAPSHOT
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: sayed/local:0.0.1-SNAPSHOT
          imagePullPolicy: IfNotPresent
          name: local
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.dekorate.io/vcs-url: <<unknown>>
    app.dekorate.io/commit-id: 9028e8e2ff5bc0171661cca72ab8acd7fe42ebd6
  labels:
    app.kubernetes.io/name: local
    app.kubernetes.io/version: 0.0.1-SNAPSHOT
  name: local
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: jmx
      nodePort: 32000
      port: 32000
      protocol: TCP
      targetPort: 32000
  selector:
    app.kubernetes.io/name: local
    app.kubernetes.io/version: 0.0.1-SNAPSHOT
  type: ClusterIP
